name: Build Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_client_x64_Debug:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset x64-linux-debug

    - name: Build
      run: cmake --build --preset x64-linux-debug

    - name: Test
      run: ctest --preset x64-linux-debug

  build_client_x64_Release:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset x64-linux-release

    - name: Build
      run: cmake --build --preset x64-linux-release

    - name: Test
      run: ctest --preset x64-linux-release

  build_server_plugin_x64_Debug:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset x64-linux-debug

    - name: Build
      run: cmake --build --preset x64-linux-debug

    - name: Test
      run: ctest --preset x64-linux-debug
  
  build_server_plugin_x64_Release:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: recursive

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake --preset x64-linux-release

    - name: Build
      run: cmake --build --preset x64-linux-release

    - name: Test
      run: ctest --preset x64-linux-release
